/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zsf_com_android_testjni_TestJNI */

#ifndef _Included_zsf_com_android_testjni_TestJNI
#define _Included_zsf_com_android_testjni_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zsf_com_android_testjni_TestJNI
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_zsf_com_android_testjni_TestJNI_Init
  (JNIEnv *, jobject);

/*
 * Class:     zsf_com_android_testjni_TestJNI
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_zsf_com_android_testjni_TestJNI_Add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     zsf_com_android_testjni_TestJNI
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zsf_com_android_testjni_TestJNI_Destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
